// Runtime access to the attested-syllable lexicon (generated by
// scripts/gen-vn-syllables.mjs from the local dictionary). This is what keeps
// the playground from ever presenting a syllable that isn't a real Vietnamese
// word: the rules say what's spellable, the lexicon says what actually exists.

import data from '../../content/vn_syllables.json';

/** Every attested syllable the builder can compose, in the builder's spelling. */
export const VALID_SYLLABLES = new Set(data.syllables);

// Tuples "initial|glide|nucleus|final" of every real base, indexed by nucleus
// (the always-present anchor) for fast reachability lookups.
const TUPLES_BY_NUCLEUS = new Map();
for (const key of data.tuples) {
    const [initial, glide, nucleus, final] = key.split('|');
    if (!TUPLES_BY_NUCLEUS.has(nucleus)) TUPLES_BY_NUCLEUS.set(nucleus, []);
    TUPLES_BY_NUCLEUS.get(nucleus).push({ initial, glide, final });
}

/** Raw tuple keys (exposed for re-export symmetry / debugging). */
export const VALID_TUPLE_KEYS = new Set(data.tuples);

/**
 * Is there a real Vietnamese base consistent with the filled structural slots?
 * `fixed` = { initial, glide, nucleus, final } where null/undefined = wildcard.
 * Needs a nucleus to judge; without one, returns true (nothing to contradict).
 */
export function canReachRealBase(fixed) {
    const nucleus = fixed.nucleus;
    if (!nucleus) return true;
    const candidates = TUPLES_BY_NUCLEUS.get(nucleus);
    if (!candidates) return false;
    const wantI = fixed.initial ?? null;
    const wantG = fixed.glide ?? null;
    const wantF = fixed.final ?? null;
    return candidates.some((t) =>
        (wantI === null || t.initial === wantI) &&
        (wantG === null || t.glide === wantG) &&
        (wantF === null || t.final === wantF));
}
